### ISSUE TITLE
Upgrade to Go 1.21

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#289]
# Task

Upgrade the Go Runtime to [1.21](https://go.dev/doc/go1.21).

## Acceptance Criteria

Development
* [x] Upgrade Go Runtime to 1.21
* [x] remove [/pkg/slices](https://github.com/primaza/primaza/tree/main/pkg/slices) in favor of (Go 1.21 slices package](https://pkg.go.dev/slices#section-documentation)
* [x] Upgrade GitHub workflows
* [x] Upgrade Dockerfiles

### Legend

- 🔲  To do
- ☑️  Done
- 🔲  ~Unsatisfied~
