### ISSUE TITLE
Add a category in GitHub Discussions for CommunityCalls

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#305]
# Task

We want to make easy for newcomers to join our community calls.
 

## In Scope

* GitHub Templates for Issue/Story/Task/Bug/Epic

## Approach

Clean and adapt to GitHub Project, the already existing templates.

## Acceptance Criteria

Development
* [ ] Update automation to create discussion with `CommunityCalls` category
* [ ] https://github.com/primaza/primaza/issues/278
* [ ] Create a category in Github Discussions for `CommunityCalls`

Docs
* [ ] Add the link to the meeting in the `CONTRIBUTING.md` file
* [ ] Add the link to the GitHub Discussion `CommunityCalls` category in the `CONTRIBUTING.md` file

### Legend

- 🔲  To do
- ☑️  Done
- ☑️  ~Unsatisfied~
